metrics:
  global:
    scrape_interval: 15s
  configs:
  - name: default
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:9090']
      - job_name: 'grpc-services'
        static_configs:
          - targets: ['payment:9000', 'inventory:9001', 'order:9002']
    remote_write:
      - url: https://prometheus-us-central1.grafana.net/api/prom/push
        basic_auth:
          username: <VOTRE_ID_UTILISATEUR_GRAFANA_CLOUD>
          password: <VOTRE_API_KEY_METRICS>

logs:
  configs:
  - name: default
    clients:
      - url: https://logs-prod-us-central1.grafana.net/loki/api/v1/push
        basic_auth:
          username: <VOTRE_ID_UTILISATEUR_GRAFANA_CLOUD>
          password: <VOTRE_API_KEY_LOGS>
    scrape_configs:
     - job_name: containers
       static_configs:
         - targets: [localhost]
           labels:
             job: docker-logs
             __path__: /var/lib/docker/containers/*/*.log

traces:
  configs:
  - name: default
    remote_write:
      - endpoint: tempo-us-central1.grafana.net:443
        basic_auth:
          username: <VOTRE_ID_UTILISATEUR_GRAFANA_CLOUD>
          password: <VOTRE_API_KEY_TRACES>
    receivers:
      otlp:
        protocols:
          grpc:
          http: