name: Deploy to EKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Amazon EKS
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurer les credentials AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # 3. Installer kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.23.15  # Doit correspondre à la version de ton cluster EKS

      # 4. Récupérer les credentials du cluster EKS
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-2 --name Anta-cluster

      # 5. Déployer les ressources Kubernetes
      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/
