name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services: [ inventory, order, payment ] 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Run tests
      run: |
        cd services/${{ matrix.service }}
        go test ./...

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ user, product, order ]  # liste les microservices

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest ./services/${{ matrix.service }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
